### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by iongion** [jshanson7/babel-plugin-resolver#7]
This is a very useful project but the last babel versions don't work with it. Do you plan on merging the pull requests or should someone fork it ?

**Comment by vdh** [comment]
@iongion Have you tried out [babel-plugin-module-alias](https://github.com/tleunen/babel-plugin-module-alias)? I've found it to be a suitable replacement for this one.

**Comment by iongion** [comment]
@vdh while that project seems as a good alternative - will try to see if it works with this project layout:

```
src
  modules
    components
    servicehelpers
      ServiceUtils.js
    EntryPoint.js
test
  modules
    components
    testhelpers
      ServiceMock.js
    EntyPoint.spec.js
```

As you can see, the NODE_PATH should be both `src/modules` and `test/modules` for the test runner because in the `EntyPoint.spec.js` one might need to import like this:

``` javascript
import ServiceMock from 'testhelpers/ServiceMock';
import ServiceUtils from 'servicehelpers/ServiceUtils';
```

So, the import resolver must look in both paths and I am not sure `babel-plugin-module-alias` allows you to do this, this project here seemed enough, simple, all one needs.

**Comment by aschrijver** [comment]
It just worked for me with babel 6.9.1 without any problems...

...but I am going to switch to babel-plugin-module-alias project ,because it gives more control and still active.

**Comment by jshanson7** [comment]
Apologies for being MIA -- I'm not actively maintaining this project, but will gladly merge pull requests.  Also happy to add collaborators.

**Comment by ghost** [comment]
@jshanson7 can you check out #8 ? :)
